# Generated by Django 3.2.25 on 2025-09-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_iso', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicateur', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='app.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('valeur', models.FloatField()),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees', to='app.indicateur')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees', to='app.pays')),
            ],
            options={
                'unique_together': {('indicateur', 'pays', 'annee')},
            },
        ),
    ]
