# Generated by Django 3.2.25 on 2025-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnee',
            name='valeur',
            field=models.FloatField(null=True),
        ),
    ]
