# Generated by Django 3.2.25 on 2025-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_donnee_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='levier',
            field=models.BooleanField(default=False),
        ),
    ]
