# Generated by Django 3.2.25 on 2025-12-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_indicateur_levier'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='direction',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative')], default='positive', max_length=10),
        ),
    ]
